name: database
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  drift: ^2.27.0
  drift_flutter: ^0.2.4

dev_dependencies:
  drift_dev: ^2.27.0
  build_runner: ^2.5.4
